### ISSUE TITLE
KeyError Unhandled error: <class 'KeyError'>, 'count', <traceback object at 0x7fec41ed67c0> 

### ISSUE THREAD

**Issue by simon-pp** [patrickchugh/terravision#100]
terravision draw --source <path to tf files> --show

Key error from debug, terraform provider is aws

`Traceback (most recent call last):
  File "terravision/terravision", line 245, in <module>
    cli(
  File "/home/simon/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/simon/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/simon/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "terravision/terravision", line 169, in draw
    tfdata = compile_tfdata(source, varfile, debug, annotate)
  File "terravision/terravision", line 72, in compile_tfdata
    tfdata = graphmaker.handle_special_resources(tfdata)
  File "terravision/modules/graphmaker.py", line 462, in handle_special_resources
    tfdata = getattr(resource_handlers, handler)(tfdata)
  File "terravision/modules/resource_handlers.py", line 154, in aws_handle_subnet_azs
    tfdata["meta_data"][az]["count"] = tfdata["meta_data"][subnet]["count"]
KeyError: 'count'`

**Comment by macindra** [comment]
It happens the same for me. Any update about this error?

**Comment by haisumriaz-tkxel** [comment]
now we stuck on this error here @patrickchugh

**Comment by Dgmmarian** [comment]
hi, any updates here?

**Comment by patrickchugh** [comment]
Working on a new version that fixes a lot of bugs will be pushed to main in 2 or 3 days

**Comment by haisumriaz-tkxel** [comment]
Thanks for the feedback! Much Appreciated!

**Comment by patrickchugh** [comment]
If you want to be sure your TF code will work please share with me so I can run tests before release the next version

**Comment by haisumriaz-tkxel** [comment]
it wasn't much, just modularised AWS specific code to create a basic vpc, and subnet to launch an ec2 instance

**Comment by AlexisDaciuk** [comment]
+1 , same error here, is that release coming soon?

**Comment by patrickchugh** [comment]
@AlexisDaciuk @haisumriaz-tkxel  can you try with the latest release?

**Comment by AlexisDaciuk** [comment]
Hi, now it fails with

Unhandled error: <class 'IndexError'>, list index out of range, <traceback object at 0x7fb3bfb0c640>

Unfortunately I won't be able to debug more this week, maybe friday, what info will be useful for debugging this?

**Comment by patrickchugh** [comment]
@simon-pp @AlexisDaciuk  @haisumriaz-tkxel  Can this issue be closed?

**Comment by patrickchugh** [comment]
Closing due to no response

**Comment by haisumriaz-tkxel** [comment]
Hi Patrick

Sorry for late response, please mark this as closed as i did not get to
work furthur on this. also ill be closing this organizational github
account. ill try again using my personal github account. if i get any
furthur issues, ill let you know in a new separate issue. Thanks you for
following up on this. Really appreciate it.

**Comment by AlexisDaciuk** [comment]
Hi,

Sorry for the late response, GitHub is not good with notifications and I did not get notified of this

I have a lot of work right now, maybe I can get to test this in the upcoming weeks, I will keep you updated
